### ISSUE TITLE
年月日の表示

### ISSUE THREAD

**Issue by organic-nailer** [codefortoda/covid19-saitama#100]
## 改善詳細 / Details of Improvement
- 年を越してしまい、統計開始からそろそろ1年が経とうとしているので月日だけでなく年の表示も必要ではないか

## 期待する見せ方・挙動 / Expected behavior
- 陽性患者数/検査数のグラフの横軸ラベル
- 陽性患者の属性の日付

**Comment by jakelizzI** [comment]
![日付ソート問題](https://user-images.githubusercontent.com/17697624/103493889-4e7fb880-4e77-11eb-8545-9dd5c5cd8a3f.png)

ソートの部分でも影響が出ていますね…
