### ISSUE TITLE
Readmeの非日本語版の文字列を、東京から埼玉に変える

### ISSUE THREAD

**Issue by showyou** [codefortoda/covid19-saitama#18]
## 改善詳細 / Details of Improvement
- Readmeの海外版がまだ東京になっていますので、修正をお願いしたいです。

**Comment by tomopict** [comment]
お疲れ様です。
見たところReadMe以外でも複数言語がありそうなものは以下でした。

CODE_OF_CONDUCT_XX.md
CONTRIBUTING_XX.md

今後の多言語展開によりますが、
翻訳を続けてアップデートしていくのが現時点では現実的ではないかと思うので、
一旦EN以外は削除してしまう方向でもいいかと思いますが、いかがでしょうか？

**Comment by showyou** [comment]
ちなみにテキスト書き換えですが、以下のコマンドで一発で出来たりします。

> grep -lr 'Tokyo' ./* | xargs sed -i "" 's/Tokyo/Saitama/g'

ただし"参照元：https://stopcovid19.metro.tokyo.lg.jp/"みたいに変えては行けないとこも変えてしまうこともあるので、そこだけは事前にgrep -r 'Tokyo' ./*とかしておいて場所を覚えておいて、後で手で修正すると良いかもしれません。

**Comment by jakelizzI** [comment]
個人的には @tomopict さんの提案であるEN以外はとりあえず削除、でいいと思っています。

他の案としては、EN以外の言語のREADMEの最初にh1タグで「正しい翻訳できてません」的な注釈を入れるような対応でもいい気がします。目的としては、開発に参加できるのであればしてほしいということと、現在ではその言語に関してサポートできないよ、ということが分かれば良いと思うので。

**Comment by tomopict** [comment]
@showyou @jakelizzI 
ありがとうございます!
参照元のようなURLのところと、`* 都庁の人だけではなく、様々な人々とともに作る`
のようなTokyo表記ではないようなところが個別で対応が必要そうです。

その辺りを考えると変な混乱を招くよりはENに関しては最低限対応、EN以外は一旦削除(今後の推移次第では復活)という流れでいいかなと思った次第です。
一旦上記の想定でPR作ってしまおうかと思います。

**Comment by showyou** [comment]
EN以外は一旦削除で良いと思います

**Comment by jakelizzI** [comment]
右に同じです！
PRお願いします！

**Comment by codefortoda** [comment]
ありがとうございます！
PR宜しくお願いします。

**Comment by showyou** [comment]
https://github.com/codefortoda/covid19-saitama/pull/19 にてdevelopmentにMergeしました。
こちらもCloseします。
