### ISSUE TITLE
データの自動更新

### ISSUE THREAD

**Issue by jakelizzI** [codefortoda/covid19-saitama#21]
## 改善詳細 / Details of Improvement
- data.jsonを自動更新させる
- 方法に関しては要検討
    - 参考 : https://tech.moyashidaisuke.com/entry/stopcovid19-auto-update

## 動作環境・ブラウザ / Environment
- ALL

**Comment by showyou** [comment]
実は #4 に同じ物が立っては居るのですが笑
スクリプトでOpendataの数値をdata.jsonに反映させるとこまでは上手く行ってますが、そこから先の更新日とか、gitへの反映とかで少し悩んでますね

**Comment by showyou** [comment]
現状ですと https://github.com/codefortoda/covid19-saitama/pull/11 がdevelopmentにmergeされれば、手動で
- $ cd tool
- $ python crawl_data.py
- $ python csv2json.py

の流れでdata.jsonが生成されます。
一旦そこまで行って、「data.jsonは自動で作ってPushは人手」を達成させた後に
北海道と同様にdata.jsonを別リポジトリに分けると言った段階に移ったほうが良いかとは思います。

(最終更新日とか取れてないので、それは改修します/してくれる方募集)

**Comment by codefortoda** [comment]
遅くなりましたが、動作確認いたしました。
$ python crawl_data.py
ではなく、
$ python crawl_opendata.py
でしたね。
生成した data.json でグラフ表示されることを確認しました。

残作業としましては、次の項目になりますでしょうか。
- 最終更新日の更新
- main_summary の更新
- 「陽性患者の属性」集計の確認
 ※「埼玉県外」等を除外しているため、県データと件数が一致していないがどうするか。

data.json を別リポジトリに分ける作業は別々に（分担して）進めても良いように思います。

**Comment by imabari** [comment]
陽性確認者一覧のPDFからCSVに変換
Pythonで作成しました
https://imabari.hateblo.jp/entry/2020/04/13/010821

**Comment by codefortoda** [comment]
@imabari 
ご対応いただきましてありがとうございます！

陽性確認者一覧のPDFからCSVに変換する処理につきましては、tool/get_from_jokyo_pdf.py でもご対応いただいておりました。（#11）
ただ、PDF URL をコマンドライン引数で渡す必要がある状態ですので、ご対応いただきましたコードを merge させていただきたいと思っています。

差し支えなければ、私の方で merge させていただきます。

**Comment by imabari** [comment]
はい大丈夫です。
その他の取得場所がよくわからなかったのでdata.jsonまでは作っていません。
取得場所がわかればdata.jsonまで作成はできると思います。

**Comment by codefortoda** [comment]
ありがとうございます！
それでは私の方で merge いたします。

**Comment by imabari** [comment]
@codefortoda 
data.jsonまで作るように変更しておきました。
オープンデータは情報が古そうでしたので取り込んでいません。

**Comment by imabari** [comment]
オープンデータからdata.jsonを作成します
https://github.com/imabari/covid19-data/blob/master/saitama/saitama_main.ipynb

**Comment by codefortoda** [comment]
陽性確認者の状況ですが、県ホームページに公開されるPDFから取得していましたが、昨日（5/7）はPDFから過去データが除外されていました。
@imabari さんにご対応いただきましたスクリプトを参考にさせていただき、オープンデータから作成するように変更しました。

データ生成は別リポジトリにし、data.json/news.jsonを定期的に自動生成するようにしています。
https://github.com/codefortoda/covid19-saitama-scraping

**Comment by imabari** [comment]
https://github.com/codefortoda/covid19-saitama-scraping/blob/8aa9718944bb2296b009db45625a5a02fa138df4/main.py#L95

文字数で変換処理変更しています

```
df_kanja["date"] = df_kanja["判明日"].apply(
    lambda x: pd.to_datetime(x, errors="coerce")
    if len(x) > 8
    else pd.to_datetime(x, format="%y/%m/%d", errors="coerce")
)
```

**Comment by imabari** [comment]
西暦が2020のときでも8文字の場合があるので
日付が202で始まるかに修正しました
```
df_kanja["date"] = df_kanja["判明日"].apply(
    lambda x: pd.to_datetime(x, errors="coerce")
    if x.startswith("202")
    else pd.to_datetime(x, format="%y/%m/%d", errors="coerce")
)
```
現在西暦が4桁のため問題ありませんが
https://github.com/codefortoda/covid19-saitama-scraping/blob/8aa9718944bb2296b009db45625a5a02fa138df4/main.py#L95

if len(x.split(',')[0]) != 2　の条件がFalseになることはないのですがなにか意味があるのでしょうか？

5/16のデータが西暦2桁のため上記試したところ日付がおかしくなります
https://opendata.pref.saitama.lg.jp/data/dataset/covid19-jokyo/resource/eae47664-cff0-4aa5-9de6-0a3ccfd0433b

**Comment by codefortoda** [comment]
ご対応ありがとうございます。
後ほどscrapingリポジトリを更新したいと思います。

> if len(x.split(',')[0]) != 2　の条件がFalseになることはないのですがなにか意味があるのでしょうか？

ご指摘ありがとうございます。x.split('/')[0]の誤りでした。。

**Comment by codefortoda** [comment]
@imabari 
すみません、ご助言をお願いしたいことがあります。

昨日（5/19）ですが埼玉県の感染者は 0 でしたが、現在の処理では patients_summary は感染者がある日付（2020-05-18）までしかできない状態です。
これを昨日の場合でしたら、「2020-05-19」（小計：0）まで生成したいのですがどのように対応したら宜しいでしょうか？
【現状生成されるデータ】
```
    "patients_summary": {
        "data": [
            {
                "小計": 1,
                "日付": "2020-02-01T08:00:00.000Z"
            },
 :
 
            {
                "小計": 2,
                "日付": "2020-05-17T08:00:00.000Z"
            },
            {
                "小計": 2,
                "日付": "2020-05-18T08:00:00.000Z"
            }
```
【期待するデータ】
```
    "patients_summary": {
        "data": [
            {
                "小計": 1,
                "日付": "2020-02-01T08:00:00.000Z"
            },
 :
 
            {
                "小計": 2,
                "日付": "2020-05-17T08:00:00.000Z"
            },
            {
                "小計": 2,
                "日付": "2020-05-18T08:00:00.000Z"
            },
            {
                "小計": 0,
                "日付": "2020-05-19T08:00:00.000Z"
            }

```

**Comment by codefortoda** [comment]
感染者 0 の対応ですがとりあえず暫定的に対応してみました。 
https://github.com/codefortoda/covid19-saitama-scraping/commit/0d1cd9085aeab206f829581546fa1b5274643901

**Comment by imabari** [comment]
順番を検査から先に処理するようにして
最終検査件数の日付が含まれない場合は0追加で処理しています
https://github.com/imabari/covid19-data/blob/master/saitama/saitama_main.ipynb

**Comment by codefortoda** [comment]
ありがとうございます！
scrapingリポジトリに反映しました。

**Comment by imabari** [comment]
あまり影響はないのですがSeriesからDataFrameへの変換方法を変更しています
reset_index、rename、dropの部分を変更
```
df_patients_sum = pd.DataFrame({"小計": ser_patients_sum.asfreq("D", fill_value=0)})
df_patients_sum["日付"] = df_patients_sum.index.strftime("%Y-%m-%dT08:00:00.000Z")
```

**Comment by imabari** [comment]
https://github.com/codefortoda/covid19-saitama-scraping/blob/1f4a6b89696f177813f256d104c8cab1b34e3033/main.py#L135

日付補完時の処理にバグがあったので修正お願いします。

陽性者の判明日と検査の最終日と重複がなく
陽性者の判明日の最終日＞検査の最終日の場合
検査の最終日までのカウントになり消えてしまいます
```
ser_patients_sum = df_kanja["date"].value_counts().sort_index()
if df_kensa.index[-1] > ser_patients_sum.index[-1]:
    ser_patients_sum[df_kensa.index[-1]] = 0
ser_patients.sort_index(inplace=True)
```

**Comment by codefortoda** [comment]
遅くなりましたが、上記の件（日付補完時の処理）と、先日、covid19-saitama-scrapingリポジトリにご提案いただいていた点（2件）を、covid19-saitama-scrapingリポジトリに反映いたしました。

**Comment by codefortoda** [comment]
covid19-saitama-scrapingリポジトリにて data.json/news.json の自動生成は対応済みですのでクローズいたします。
https://github.com/codefortoda/covid19-saitama-scraping

※今後は 自動生成に関して何かございましたら、covid19-saitama-scrapingリポジトリへ issue を挙げていただけたらと思います。
