### ISSUE TITLE
READMEの「ステージング・本番環境への反映」のリンクが間違っている

### ISSUE THREAD

**Issue by jakelizzI** [codefortoda/covid19-saitama#22]
## 起こっている問題 / The Problem
- 本番サイトへのリンク先は正しいが、文字表示がおかしい -> https://saitama.stopcovid19.jp/
- stgとdevは「Not Found」

## 期待する見せ方・挙動 / Expected Behavior
- 正しいリンクに修正

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by jakelizzI** [comment]
ブランチと挙動の確認がしたいです！


## 挙動 

mergeをトリガーにそれぞれの環境にデプロイ

## ブランチについて

* master -> 本番サイト
* development -> dev環境
* staging -> ??? 無い

**Comment by codefortoda** [comment]
現在は次の通りです。
- master -> https://saitama.stopcovid19.jp/
- development -> https://dev-stopcovid19.e-toda.jp
- staging -> 環境を用意していません。
