### ISSUE TITLE
使用していない tokyo-metropolitan-gov/covid19 由来の PHP スクリプトを削除したい

### ISSUE THREAD

**Issue by ariarijp** [codefortoda/covid19-saitama#32]
## 改善詳細 / Details of Improvement
- 新しく開発に参加しようとした開発者に混乱をあたえないよう、使用していないファイルを削除したい

## スクリーンショット / Screenshot
- なし

## 期待する見せ方・挙動 / Expected behavior
- covid-19-saitama で使用するファイルのみが tool ディレクトリに存在している

## 動作環境・ブラウザ / Environment
- なし

**Comment by showyou** [comment]
Let's do Pull Request.

**Comment by codefortoda** [comment]
以前、私が merge しておりました。失礼しました。
削除いただきありがとうございます。
