### ISSUE TITLE
ちょっとしたドキュメント中の typo 修正

### ISSUE THREAD

**Issue by ariarijp** [codefortoda/covid19-saitama#33]
## 改善詳細 / Details of Improvement
- ドキュメント中に typo がいくつか見られたので、全体的に見直して修正したい
 - blob/development/.github/CONTRIBUTING.md の `Pull Reuqest` など

## スクリーンショット / Screenshot
- なし

## 期待する見せ方・挙動 / Expected behavior
- 各ドキュメントから typo と思われるものがなくなっている・対応前よりも減っている

## 動作環境・ブラウザ / Environment
- なし

**Comment by ariarijp** [comment]
@codefortoda こちら進めちゃってもよいでしょうか？やったところでユーザーには直接的にメリットないので、このまま Close しちゃってもよいです。

**Comment by codefortoda** [comment]
@ariarijp 
typoのまま残しておくと混乱が生じる可能性がありますので、すみませんが修正をお願いします。
