### ISSUE TITLE
検査陽性者の表示に縦線が描画される

### ISSUE THREAD

**Issue by paichi81** [codefortoda/covid19-saitama#35]
## 起こっている問題 / The Problem
- 検査陽性者の表示に縦線が描画される(ことがある)

## スクリーンショット / Screenshot

- ビューポートの水平解像度が1913pxのとき
![image](https://user-images.githubusercontent.com/4400857/78525162-4ffd5100-7811-11ea-8feb-745b11a9af85.png)

- ビューポートの水平解像度が1442pxのとき
![image](https://user-images.githubusercontent.com/4400857/78525297-b7b39c00-7811-11ea-96d1-bb907612f17c.png)

## 期待する見せ方・挙動 / Expected Behavior
- 縦線がでないようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. おおきなビューポートで開く

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

### その他
オリジナルのtokyoサイトで確認したところ、同様の事象は発生しませんでした。
あわせてオリジナルのissueも検索してみましたが、同様の内容は見つかりませんでした。
最新のコードベースにあわせると治るのかもしれません。

**Comment by kimitaka** [comment]
こちら同様の現象を確認しました。

- Windows 10 Pro 64bit バージョン1909 ビルド18363.720
- Google Chrome 80.0.3987.163 (Official Build) (64bit)

**Comment by codefortoda** [comment]
#103 で表示方法を変更（項目「横並び」→「縦並び」）した関係で、こちらの現象が解消したと思います。

**Comment by codefortoda** [comment]
#103 の表示方法変更に伴い、こちらの現象は発生していない状態だと思いますのでクローズいたします。
