### ISSUE TITLE
サイトのロゴの埼玉県の形を埼玉県章に変更

### ISSUE THREAD

**Issue by peijun** [codefortoda/covid19-saitama#36]
## 改善詳細 / Details of Improvement
- サイトのロゴの埼玉県の形を埼玉県章に変更

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

他県でも県章を用いており、いらすとやさんの規約とMITライセンスの競合問題(#31 で言及されている問題)も解消される
この件に関して埼玉県に問い合わせる必要があると思うのですがCode for TODA様に問い合わせていただくのがよろしいかと思っております

**Comment by peijun** [comment]
@codefortoda すみません。知人のデザイナー様の話と同時にIssueを立ててしまいました。もしよろしければご検討のほどよろしくお願いします。

**Comment by paichi81** [comment]
Wikipediaの埼玉県で使用されている県章SVG画像はパブリックドメインみたいですね

**Comment by codefortoda** [comment]
issue 立てありがとうございます。

埼玉県章ですが 2015/1/1よりパブリックドメインとなっていますので利用は可能と思いますが、まだ非公式のため、混乱を招いてしまう恐れもあると思いまして使用していませんでした。

ちなみに、「県章がカッコいい都道府県」で１位なので、何かしら利用できたらと思っています。
https://j-town.net/tokyo/research/results/292387.html?p=2

**Comment by peijun** [comment]
パブリックドメインの件教えていただきありがとうございます。また県章を利用してない理由も把握いたしました。
埼玉県から公式とは言わないまでも公認を受けて県章を利用するのは良いのかなと思いました
いずれにせよ良い形で利用できるよう自分も考えてみます
コメントありがとうございます

**Comment by codefortoda** [comment]
知人のデザイナーにロゴを作成していただきました。３案あります。

検討段階のロゴを公開の場で議論するのは抵抗がありましたので、現在、Code for TODAのSlackでみなさんのご意見を確認しています。
もし宜しければ、Slackワークスペースへご参加ください。
https://codefortoda-slackin.herokuapp.com/

メール等でロゴ案をお送りすることも可能です。ご希望の方はご連絡ください。

**Comment by codefortoda** [comment]
サイトロゴを独自デザインに変更しました。 #50 
ご確認のほど宜しくお願いします。
