### ISSUE TITLE
県のオープンデータが 3/31 以降更新されていない

### ISSUE THREAD

**Issue by ma2gedev** [codefortoda/covid19-saitama#37]
3/31 以降下記ページのデータが更新されておらず、本サイトの更新も手作業で大変ではないでしょうか。中の人の手が回っていないだけかもしれませんが、念のため今後どうなるのか自分の方で問い合わせをしてみます。

https://opendata.pref.saitama.lg.jp/data/dataset/covid19-jokyo

**Comment by showyou** [comment]
こちらですが、既に私から県に問い合わせを行い、本日対策を行う返信を頂いております。

**Comment by ma2gedev** [comment]
ありがとうございます。では私の方ではアクション取らないでおきます。ほかの方が状況把握できるように、チケットのクローズはまだしないでおきます。

**Comment by showyou** [comment]
ありがとうございます！

**Comment by ma2gedev** [comment]
こちら https://opendata.pref.saitama.lg.jp/data/dataset/covid19-jokyo のページが更新されていることを確認しました。交渉ありがとうございます！こちらはクローズします。
