### ISSUE TITLE
感染状況ページからの軽症重症患者数の抜き出し

### ISSUE THREAD

**Issue by showyou** [codefortoda/covid19-saitama#38]
## 起こっている問題 / The Problem

- Opendataだけだと軽症重症患者の数が取得できないので、http://www.pref.saitama.lg.jp/a0701/shingatacoronavirus.html をスクレイピングして軽症重症患者数を取得する

## 期待する見せ方・挙動 / Expected Behavior
- <img width="725" alt="患者数の部分" src="https://user-images.githubusercontent.com/18357/78555017-2828e000-7847-11ea-971b-b07814f9870a.png">
↓
> 186, 152,145, 7, 31, 3

と書かれたpatients_YYYYMMDD.csv(YYYYMMDDは20200405みたいな日付)を出力するプログラム

## 動作環境・ブラウザ / Environment
- Linux
- Python / Beautifulsoup4

**Comment by showyou** [comment]
こちらですが、県の方がOpendataで出してくれることになりそうなので、不要になりそうです。

**Comment by codefortoda** [comment]
covid19-saitama-scrapingリポジトリにて、スクレイピングして取得するように対応しておりますので、issue をクローズしたいと思います。
