### ISSUE TITLE
サイトを「やさしい にほんご」で表示できるようにする

### ISSUE THREAD

**Issue by kimitaka** [codefortoda/covid19-saitama#39]
## 改善詳細 / Details of Improvement
- サイトを「やさしい にほんご」で表示できるようにする
  - i18n対応を行う
    - プロジェクトのフォーク元である[東京都版のサイトでは nuxt-i18n を利用している](https://github.com/tokyo-metropolitan-gov/covid19/blob/f8d2569903a51f6eaabda178f158718ec2ea8b2c/nuxt.config.ts#L104)ので、それを踏襲するのが妥当か
    - [nuxt-i18n のGitHubリポジトリ](https://github.com/nuxt-community/nuxt-i18n)
  - サイト内の文言を「やさしい にほんご」に翻訳する
    - [外国人にやさしい日本語表現の手引](https://www.pref.saitama.lg.jp/a0306/tabunkakyousei/yasasiinihongo.html)

## スクリーンショット / Screenshot
東京都版のサイトのスクリーンショットを参考例として掲載します

![東京都（とうきょうと）での コロナウイルスの あたらしい じょうほう _ 東京都 新型コロナウイルス感染症対策サイト - Google Chrome 2020_04_06 20_34_53 (2)](https://user-images.githubusercontent.com/167225/78555406-ec424a80-7847-11ea-822a-98cddc8e4335.png)

## 期待する見せ方・挙動 / Expected behavior
- サイトを「やさしい にほんご」で表示できるようにし、日本語を母国語としない人々でも利用しやすくする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

## 備考
この提案の件ですが、まだ具体的なコードは書いていません。私は Vue.js や Nuxt.js 等の開発経験がないので、今必要なドキュメントを読み込んでいるところです。
「改善詳細」の段落に記述した大まかな対応方針に関して、アドバイスをいただけると助かります。

または、可能であればi18n対応部分をほかの人に分担して作業していただけると嬉しいです。

**Comment by showyou** [comment]
ご存知かも知れませんが、元のTokyoのサイトはTrasifixというサイトを使って翻訳作業を行っています。
これを上手く活用できる形でnuxt-i18nを呼んであげると良さげです。

**Comment by nanchovy** [comment]
こんばんは、こちらの翻訳に関する作業をお手伝いしたいです。
transifex上でプロジェクトをすでに立ち上げた方はいらっしゃいますでしょうか？まだであれば私が立ち上げてみます。
また、やさしい日本語の他に英語での表示も行えるようにしたいのですが、その場合は別にissueを立てるのが適切でしょうか。

**Comment by codefortoda** [comment]
@nanchovy 
ありがとうございます！大変助かります。

> transifex上でプロジェクトをすでに立ち上げた方はいらっしゃいますでしょうか？まだであれば私が立ち上げてみます。

私が把握しているかぎり、まだ立ち上げていない状態です。

> また、やさしい日本語の他に英語での表示も行えるようにしたいのですが、その場合は別にissueを立てるのが適切でしょうか。

"やさしい日本語"と"英語"をまとめてご対応される場合はそのままでも良いと思いますが、もし別に作業を進められるようでしたら issue を分けていただけますでしょうか。

**Comment by paichi81** [comment]
こちら進捗ありますか？
Slackのほうで書きましたが、現在の埼玉版がTransifex利用以前からのフォークだとおもうので、現在の版から手パッチしたものを概ねレベルで作ってみました（データのほうで対応してもらう必要があります）
en localeもある程度Tokyo→Saitamaに直しているので、いくつか流用できるのではないかと思います。別途進んでいるようでしたら、そちらでお手伝いします。

https://github.com/paichi81/covid19-saitama-dev

**Comment by nanchovy** [comment]
@paichi81さん、こんにちは。
今終わっている作業は
- transifexとの連携
- 各vueファイルのi18nタグを削除
- トップページへの多言語対応選択メニューの追加

現在残っている作業は
- tokyo -> saitamaへの訳語変換
- 陽性患者の属性カードが翻訳未対応なので対応させる
- transifexからcovid-saitamaリポジトリへの自動更新(優先度低)
です。

特にtokyo->saitamaへの訳語変換を今日行おうとしていたところだったので、大変助かります。
transifexのリンクはこちらです。
https://www.transifex.com/stopcovid19-saitama/stopcovid19Saitama/
まずはtransifexへの訳語の登録を私の方で行ってもよろしいでしょうか。

**Comment by kimitaka** [comment]
@paichi81 さん
@nanchovy さん
ご対応ありがとうございます。

そしてすいません、言い出しっぺなのに全然作業が進んでおりませんでした。

@paichi81 さんのレポジトリと、埼玉県版のtransfixプロジェクトを拝読致しました。
後はnuxt-i18nによって文言の出し分けができる様になれば良い感じでしょうかね？
既に着手済みでしたらそのままお願い致します。
未着手でしたら東京都版のi18n対応の実装を埼玉県版に持ってくる作業を私が行います。

**Comment by nanchovy** [comment]
@kimitaka さん、issueを立てていただきありがとうございます。

あとは東京都版の翻訳のjsonファイルのうち、埼玉県版に合わせた文言に編集する作業となります。英語版はpaichi81さんに作業していただいたものが使えるのですが、transifexの都合上、日本語版から編集しなければいけません。現在その日本語版の編集をしているところです。

まだtransifexの仕様をあまり理解しきれていないために、現在私のPC上で日本語版編集の作業を行なっています。今後分担できる作業(paichi81さんに追加していただいた単語をtransifex上でやさしい日本語に翻訳するなど)が発生しますので、その際に作業いただけるとありがたいです。

**Comment by paichi81** [comment]
自分が見直していたときも、実際には利用しない部分があり、見直すのに結構時間がかかりました。
このあたりはコンポーネントの使い方ふくめ確認したほうが無駄がないのかもしれません。
一度slackで進め方をCode for Todaのメンバに相談したほうがいいかもですね。

**Comment by kimitaka** [comment]
なるほど、闇雲に手を動かすよりかは相談した方が良さそうですね。

@codefortoda
お手数ですが、差し支えなければSlackのワークスペースに招待していただけませんでしょうか？
あと、CONTRIBUTING.mdに記載されているSlackワークスペースが Code for Japan の物になっていますが、 Code for Toda のものに差し替えるか追記をした方が良いかも知れません。

**Comment by nanchovy** [comment]
そうですね。実際利用しない部分の中にはそのまま利用してしまうと大きな誤解を生んでしまう部分もあります。
(paichi81さんはご存知と思いますが)pages/worker.vueには
>感染症により事業活動に影響を受けている中小企業等を対象とした制度融資（「緊急融資」、「緊急借換」、「危機対応融資」）です。いずれも融資限度額は2億8千万円で、信用保証料を都が補助します。

とあります。これはそのままにしておくと誤解を生む可能性がかなり高いため、翻訳のkeyごと削除するのが適切だと思います。

また、各vueファイルでテキスト置換に用いているkeyは基本東京都で使用している文章なので、何処かのタイミングでまとめて埼玉県用の文章に直したいですね。

以上二点については今回は編集せずに進めていますが、翻訳作業がひと段落したら別issueで対応したいと思います。

**Comment by codefortoda** [comment]
@kimitaka 
Code for TODAのSlackは次のURLからご参加ください。
招待リンク：https://codefortoda-slackin.herokuapp.com/
※チャンネルは #stopcovid19jp になります。

CONTRIBUTING.md のご指摘ありがとうございます。
修正の issue を立てたいと思います。

**Comment by codefortoda** [comment]
@paichi81 
https://github.com/paichi81/covid19-saitama-dev を確認させていただきました。
表示色変えられたのですね。※最初見た時一瞬焦りました。。

私の環境だけもしれませんが、表示されるまでにかなりの時間がかかりました。
paichi81 さんの環境では表示速度は特に問題ない感じですか？

**Comment by paichi81** [comment]
一旦みわけを付ける意味も兼ねて、コバトンカラーにしました。
東京はgreen-*で色を直に指定していますが、variables.scssでグラフ・表等の色を一括変更できるようにしてもあります($siteThemeColor-*)

表示までの時間ですが、初回けっこうかかりました。
新版がそうなのか、東京のデータが重いからなのか、多言語localeの読み込みが重いのか検証できていませんが、yarn起動時に相当メモリ食いますね。
yarn dev-no-axeで少しだけかるくなりますが、体感ベースでどちらも重いです。

**Comment by codefortoda** [comment]
私の環境だけではなかったようでちょっと安心しました。
yarn dev-no-axe を試してみたいと思います。

色はコバトンカラーでしたか！
最初に作業を進めたころはコバトンか、県章の勾玉の色をベースにしようかなと思ってたのですが、サイトを公開する時には余裕がなくて、東京のままに公開してしまいました。。
