### ISSUE TITLE
「陽性患者の属性」から退院欄の削除

### ISSUE THREAD

**Issue by showyou** [codefortoda/covid19-saitama#40]
## 改善詳細 / Details of Improvement
- 陽性患者が入院しているかどうかの情報は、今後プライバシーの観点から提供しないことを県の担当者からお伺いしました。
現状のままですと退院した患者が減ってないように見えるので、退院欄は取り除いた方が良さそうです。

## スクリーンショット / Screenshot
<img width="403" alt="陽性患者の属性欄" src="https://user-images.githubusercontent.com/18357/78618285-fa7a8000-78b4-11ea-98c8-2edcb29447f2.png">

## 期待する見せ方・挙動 / Expected behavior
退院欄を取り除く

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nanchovy** [comment]
はじめまして。こちら実装してみます。
