### ISSUE TITLE
陽性患者のステータス(退院等)の表示

### ISSUE THREAD

**Issue by kachine** [codefortoda/covid19-saitama#48]
## 改善詳細 / Details of Improvement
- 2020/4/7のdata.jsonのコミット以降、陽性患者の属性表から患者のステータス(退院)が削除されている。(これがデグレードなのか、プライバシー等への配慮を意図した対応なのか判断できません。)
- 県のOpenDataのCSVにも3/30までは現状列(退院/入院中/入院予定)が存在していたが、しばらくOpenData自体の更新が途絶え、更新再開された4/7断面では当該列が消えている。
https://opendata.pref.saitama.lg.jp/data/dataset/covid19-jokyo
- NHK報道によれば以下の通りで、自宅待機を余儀なくされている患者が存在する。この状況(及び今後の改善または悪化具合を)を県民が把握できるようにするためにも、患者のステータスは今後も開示されるべきではないか。

>一方、埼玉県はこれまでに県内で感染が確認された人のうち、医療機関に入院せず、自宅で待機している人が８日午後６時の時点で78人いることを明らかにしました。

https://www3.nhk.or.jp/news/html/20200408/k10012376671000.html?utm_int=news-ranking_social_list-items_007

## 期待する見せ方・挙動 / Expected behavior
- 患者のステータス表示の復活(ステータスに自宅待機も追加)

**Comment by codefortoda** [comment]
陽性患者のステータス（退院等）ですが、プライバシー保護の観点から提供されないことになりました。（詳細は #40 をご確認ください）
そのため、#43 で「陽性患者の属性」から退院欄を削除しています。

**Comment by kachine** [comment]
ご回答ありがとうございます。
陽性患者毎のステータスはプライバシー保護の観点から表示できない旨、承知いたしました。

県からのデータ提供が無ければ不可能なため、こちらで要望するのが適切か判りませんが、サマリ済の値を県から提供いただくなどして、各ステータス(入院中/退院済/自宅待機中/死亡)を居住地、或いは県全体でサマリした値を表示することはできないでしょうか？
(別issueとして起票した方がよろしければご指摘ください。本issueはcloseします。)

- サマリ値の表示イメージ

|居住地|患者の状況|人数|
|---|-----|--|
|○○市|入院中|3|
|○○市|退院済|5|
|××市|自宅待機中|2|

※居住地メッシュでの表示もプライバシー保護の観点から不可の場合、県全体のサマリ値でも可。

**Comment by codefortoda** [comment]
NHK報道の内容を見る限り、県全体の数値であればご提供いただける可能性は高そうですね。

タイトルと内容が異なってきましたので、こちらの issue は close していただきまして、別 issue を立てていただけたらと思います。

**Comment by kachine** [comment]
お忙しいところ、ご回答いただきありがとうございました。
https://github.com/codefortoda/covid19-saitama/issues/49 として改善要望を起票いたしましたので、本issueはcloseとさせていただきます。
