### ISSUE TITLE
検査数のソースのリンク名を修正

### ISSUE THREAD

**Issue by showyou** [codefortoda/covid19-saitama#56]
## 改善詳細 / Details of Improvement
related: #54 
検査数が追加されましたが、検査数の出典の部分のリンク名が「発生状況」になっています

## スクリーンショット / Screenshot
<img width="831" alt="link" src="https://user-images.githubusercontent.com/18357/79041919-70247a00-7c2e-11ea-9683-117a44d2ea50.png">

## 期待する見せ方・挙動 / Expected behavior
スクリーンショットの赤線部のリンクを「発生状況」から「検査数」に変えてください。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by showyou** [comment]
@ma2gedev こちらに別issue立てました。
「作業を行ってくれ」と決めつけるものでもございませんので、Assignはしないでおきます。
(対応頂けると大変助かります)

**Comment by ma2gedev** [comment]
別立てしてくれてありがとうございます。せっかく途中まで対応したので、引き続き対応しちゃいますね。

**Comment by ma2gedev** [comment]
#57 で対応しました
