### ISSUE TITLE
英語/やさしいにほんご時に、「カード見出し」と「実績値」の文字が重なる

### ISSUE THREAD

**Issue by cookie-maker** [codefortoda/covid19-saitama#77]
## 起こっている問題 / The Problem
- 英語/やさしいにほんご時に、「カード見出し」と「実績値」の文字が重なって表示される

### 英語表示時
![image](https://user-images.githubusercontent.com/3675067/80921003-649c1d00-8dae-11ea-8cd5-1ad29dce87f9.png)

### やさしいにほんご時
![image](https://user-images.githubusercontent.com/3675067/80921072-cf4d5880-8dae-11ea-82de-237ebe3d2f7d.png)

![image](https://user-images.githubusercontent.com/3675067/80921024-88f7f980-8dae-11ea-8387-a3cf368de4f8.png)

## 起こっている問題の再現手段 / Steps to Reproduce
ウインドウサイズ変更も行いましたが、以下該当時は常に重なって表示されています。

- 陽性患者数（やさしいにほんご）
- 埼玉県が実施した新型コロナウイルス疑い例検査数（英語/やさしいにほんご）

## 動作環境・ブラウザ / Environment
- Windows
- Chrome / Firefox

**Comment by youkidearitai** [comment]
- `.DataView-DataInfo-date`の`white-space: nowrap` をとる
- `.DataView-DataInfo`に`width: 50%`
- `.DataView-TitleContainer.with-infoPanel`にwidth: 50%`

とすれば行けそうな気がします。


![Screenshot_2020-06-06 埼玉県 新型コロナウイルス感染症対策サイト(1)](https://user-images.githubusercontent.com/305368/83906837-42c3fa80-a79f-11ea-8a34-5aa6a5d568dc.png)

![Screenshot_2020-06-06 埼玉県 新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/305368/83906812-393a9280-a79f-11ea-860d-3015c9eae81a.png)
