### ISSUE TITLE
TOPに表示されているグラフが見にくくなっているので見やすくする

### ISSUE THREAD

**Issue by jakelizzI** [codefortoda/covid19-saitama#79]
## 改善詳細 / Details of Improvement

- TOPに表示されているグラフが見にくくなっているので見やすくする
- Issue #58 と似ていますが、どのような方法がベスト（楽）かも含めてこのIssueで決めていただければと思います。

## 期待する見せ方・挙動 / Expected behavior

- 幅を決めてドラッグできるようにする
- 幅を決めれるようにする（#58 のスクリーンショットのような？）

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by organic-nailer** [comment]
ざっと見た限りですが、スライダー方式だと
北海道 https://stopcovid19.hokkaido.dev/ は#58 の方式で標準が全期間・最低14日間で指定できます。
愛知県 https://stopcovid19.code4.nagoya/ は同様の方式で標準が2ヶ月・最低期間なしで指定可能
福岡県 https://fukuoka.stopcovid19.jp/ 標準が2ヶ月・最低14日間で指定可能

東京都 https://stopcovid19.metro.tokyo.lg.jp/ は横にドラッグできる形です。

みやすさと利便性(アニメーション等)を考えると北海道方式が良いと思うのですが、どうでしょうか。

**Comment by codefortoda** [comment]
各サイトを調査・比較していただきましてありがとうございます。参考になりました！
ご提案いただきました 北海道方式がわかりやすくて良さそうですね。

**Comment by codefortoda** [comment]
#82 でご対応いただきましたので、close します。
