### ISSUE TITLE
Edgeでバーチャートに黒いバーが出てくる

### ISSUE THREAD

**Issue by youkidearitai** [codefortoda/covid19-saitama#83]
## 起こっている問題 / The Problem
- Edge0人のときに、バーチャートに黒いバーが出てくることを見つけました。
  - (現行のEdgeHTMLベースのもので、新しいChroniumベースのEdgeでは出てこないです)

## スクリーンショット / Screenshot

![covid-19-site-0-is-0000-on-edgehtml](https://user-images.githubusercontent.com/305368/85920250-25211700-b8ad-11ea-9b86-120b75dac729.png)

## 期待する見せ方・挙動 / Expected Behavior
- 0人の際には、他ブラウザと同じように透明とする

## 起こっている問題の再現手段 / Steps to Reproduce
1. Edgeブラウザで閲覧する

## 動作環境・ブラウザ / Environment
- Windows
- Edge (Microsoft Edge 44.19041.1.0, Microsoft EdgeHTML 18.19041)

**Comment by codefortoda** [comment]
#84 でご対応いただきましたので close します。
