### ISSUE TITLE
パフォーマンス改善

### ISSUE THREAD

**Issue by codefortoda** [codefortoda/covid19-saitama#99]
## 起こっている問題 / The Problem
- お問い合わせメール宛に、表示に時間がかかる（10秒程度）とご指摘あり。
ご利用環境：
　・ＰＣ(WINDOWS10)
　・Chrome
　・ネットワ－クは光回線
色々な時間帯にご利用いただいているが、常時発生している状況。
- 他県のCOVID19状況もご確認いただいているが、埼玉が一番遅い。
※北海道・東京・千葉・神奈川・愛知・大阪・兵庫・京都・福岡・沖縄

## 期待する見せ方・挙動 / Expected Behavior
- パフォーマンスを改善する。

**Comment by codefortoda** [comment]
他サイトを確認したところ、ページング機能を追加してパフォーマンス改善を行なっている。
https://github.com/tokyo-metropolitan-gov/covid19/pull/3868

**Comment by paichi81** [comment]
東京都はdata.jsonのほうにも手を入れたようなissueがあるようです。
https://github.com/tokyo-metropolitan-gov/covid19/issues/5245
